name: eeg-brain-age
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pyyaml
  - pandas
  - numpy
  - scipy
  - pyarrow
  - mne
  - mne-bids
  - pip
  - pip:
    - openneuro-py
